# Generated by Django 5.2 on 2025-04-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpconnection',
            name='content_type',
            field=models.CharField(choices=[('json', 'JSON File'), ('csv', 'CSV File'), ('xml', 'XML File')], default=None, max_length=255),
        ),
    ]
